services:
  backend:
    container_name: backend
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    restart: always
    environment:
      - ALLOWED_HOSTS=backend,localhost,ciso.attackscore.com
      - CISO_ASSISTANT_URL=https://localhost:8443
      - DJANGO_DEBUG=True
      - AUTH_TOKEN_TTL=7200
      - DEFAULT_FROM_EMAIL=ciso@attackscore.com
      - EMAIL_HOST=smtp.sendgrid.net
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=apikey
      - EMAIL_HOST_PASSWORD=(key)
      - EMAIL_USE_TLS=True
    volumes:
      - ./db:/code/db

  frontend:
    container_name: frontend
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api
      - PUBLIC_BACKEND_API_EXPOSED_URL=https://ciso.attackscore.com:8443/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host

    image: ghcr.io/intuitem/ciso-assistant-community/frontend:latest
    depends_on:
      - backend

  caddy:
    container_name: caddy
    image: caddy:2.8.4
    environment:
      - CISO_ASSISTANT_URL=https://ciso.attackscore.com
    depends_on:
      - frontend
    restart: unless-stopped
    ports:
      - 443:443     # Standard HTTPS port
      - 8443:8443
    volumes:
      - ./caddy_data:/data
      - /etc/letsencrypt/live/ciso.attackscore.com/fullchain.pem:/etc/caddy/certs/ciso.attackscore.com.crt:ro
      - /etc/letsencrypt/live/ciso.attackscore.com/privkey.pem:/etc/caddy/certs/ciso.attackscore.com.key:ro
    command: |
      sh -c 'echo $$CISO_ASSISTANT_URL "{
      tls /etc/caddy/certs/ciso.attackscore.com.crt /etc/caddy/certs/ciso.attackscore.com.key
      reverse_proxy /api/* backend:8000
      reverse_proxy /* frontend:3000
      tls internal
      }" > Caddyfile && caddy run'
